server:
  port: 8080
spring:
  application:
    name: ujcms-items
  profiles:
    active: test
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xinghuo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 419520
  redis:
    host: 110.40.211.224
    port: 6379
    password: 419520
    database: 0
  cache:
    redis:
      time-to-live: 1800000  #设置缓存时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
        # 1 代表已删除，不配置默认是1，也可修改配置
        logic-delete-value: 1
        # 0 代表未删除，不配置默认是0，也可修改配置
        logic-not-delete-value: 0


