server:
  port: 8081
spring:
  application:
    name: ujcms-items
  profiles:
    active: test
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://110.40.211.224:3306/ujcms-table?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 419520
    mvc:
      static-path-pattern: /static/**
  redis:
    host: 110.40.211.224
    port: 6379
    password: 419520
    database: 0
  cache:
    redis:
      time-to-live: 1800000  #设置缓存时间

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jackson:
    #指定日期格式，比如yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    #指定日期格式化时区
    time-zone: GMT+8
jwt:
  route:
    authentication:
      path: /login
  #  header: Authorization
  header: token
  expiration: 604800
  secret: Authorization

#FTP:
#  ADDRESS: 110.40.210.213
#  PORT: 21
#  USERNAME: images
#  PASSWORD: HN5ptkP4xJxWpwhE
#  BASEPATH: www/wwwroot/images
#  URL: http://110.40.210.213/img
# minio 参数配置
minio:
  endpoint: http://43.138.119.32:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test


#freemarker配置
freemarker:
  allow-request-override: false
  check-template-location: false
  request-context-attribute: req  #req访问request
  suffix: .ftlh  #后缀名
  content-type: text/html
  expose-request-attributes: true
  expose-session-attributes: true
  enabled: true
  cache: false #缓存配置
  template-loader-path: classpath:/templates/ftl #模板加载路径 按需配置
  charset: UTF-8 #编码格式
  number_format: '0.##'   #数字格式化，无小数点


#  #html存放的具体路径，可进行自定义，示例：resources/templates
#  #  spring.thymeleaf.prefix=classpath:/templates/
#  #  spring.thymeleaf.encoding=UTF-8
#  #  spring.thymeleaf.cache=false
#  #  spring.thymeleaf.suffix=.html
#  #  spring.thymeleaf.servlet.content-type=text/html
#  thymeleaf:
#    prefix: classpath:/static/
#    encoding: UTF-8
#    cache: false
#    suffix: .html
#    servlet:
#      content-type: text/html
#    check-template-location: true



